### ISSUE TITLE
Test on Safari in macOS 12.4 and ios 15.5

### ISSUE THREAD

**Issue by riflowth** [rootEnginear/safari-bug-i-encountered#1]
Device
- Safari 15.5 on macOS 12.4 (Monterey)
- ios 15.5 on iPhone

Everything works perfectly
- Gradient text is fine
- Input radio type doesn't need to click twice

NOTE:
> Your solution will help me with backward compatibility for web development if you provide Safari version that causes the bug

**Comment by rootEnginear** [comment]
ปัญหาก็คือ reproduce ไม่ได้นี่แหละ 555555 จะบ้าตายรายวัน
